
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_ide?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  #    url: jdbc:h2:mem:~/web_ide
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
