spring:
  application:
    name: notification-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: notification-group-${random.uuid}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        fetch.min.bytes: 1
        fetch.max.wait.ms: 100
        max.poll.records: 500
        session.timeout.ms: 45000
        heartbeat.interval.ms: 3000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
