
spring:
  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://localhost:3306/test?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: root
#    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
