logging:
  level:
    root: INFO

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379

