
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 182476236485-ncpr7mpl8dh2aksjkuvt4d657c2dt50h.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id: 6cBwnCiZRMIENieVPZxs
            client-secret: 60wlH9Bb_X
            client-name: naver-client-app
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: email, profile

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

token:
  header_string: Authorization
  prefix: Bearer
  expiration_time: 864000000
  secret: test
