services:
  mysql_shard1:
    image: mysql:8.0
    container_name: mysql_shard1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shard1_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - shard_network
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_shard2:
    image: mysql:8.0
    container_name: mysql_shard2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shard2_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
    networks:
      - shard_network
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_shard3:
    image: mysql:8.0
    container_name: mysql_shard3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shard3_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3309:3306"
    networks:
      - shard_network
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  shard_network:
    driver: bridge
