
spring:
#  session:
#    store-type: redis
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/test?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

#server:
#  port: 0
