spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  app:
    jwtSecret: jwtSecretKey

