spring:
  profiles:
    active: mysql

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  batch:
    jdbc:
      initialize-schema: always
