server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/socialLogin
    username: root
    password: 1234

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 182476236485-ncpr7mpl8dh2aksjkuvt4d657c2dt50h.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: 6cBwnCiZRMIENieVPZxs
            client-secret: 60wlH9Bb_X
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: profile,email

#          kakao:
#            client-id: 64979b3f8185261981d7118e66259305
#            client-secret: tRy7I3nu6NhxbjmSFV35mnf10uUZYmew
#            authorization-grant-type: authorization_code
#            client-name: client-app
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            scope: profile,email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

#            kakao:
#              issuer-uri: https://kauth.kakao.com
#              authorization-uri: https://kauth.kakao.com/oauth/authorize
#              token-uri: https://kauth.kakao.com/oauth/token
#              user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
#              jwkSetUri: https://kauth.kakao.com/.well-known/jwks.json
#              user-name-attribute: id
