server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 1234

logging:
  level:
    org.hibernate.SQL: debug