spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sqlprac
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        use_sql_comments: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

kogpt-api:
  host: "https://api.kakaobrain.com"
  endpoint: "/v1/inference/kogpt/generation"
