server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 1234
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}\Desktop\inflearn\spring-cloud\Work\native-file-repo
#        git:
#          uri: file:///C:\Users\user\Desktop\inflearn\spring-cloud\Work\git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh