spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    master:
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test
    slave:
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/test
